In [2]:
with open("/home/onyxia/work/cache/ValeursFoncieres-2024.txt", "r", encoding="utf-8") as f:
    for i in range(10):
        print(f.readline().strip())

Identifiant de document|Reference document|1 Articles CGI|2 Articles CGI|3 Articles CGI|4 Articles CGI|5 Articles CGI|No disposition|Date mutation|Nature mutation|Valeur fonciere|No voie|B/T/Q|Type de voie|Code voie|Voie|Code postal|Commune|Code departement|Code commune|Prefixe de section|Section|No plan|No Volume|1er lot|Surface Carrez du 1er lot|2eme lot|Surface Carrez du 2eme lot|3eme lot|Surface Carrez du 3eme lot|4eme lot|Surface Carrez du 4eme lot|5eme lot|Surface Carrez du 5eme lot|Nombre de lots|Code type local|Type local|Identifiant local|Surface reelle bati|Nombre pieces principales|Nature culture|Nature culture speciale|Surface terrain
|||||||000001|02/01/2024|Vente|346,50||||B020|LE DELIVRE|1230|CHALEY|01|76||B|514||||||||||||0||||||P||99
|||||||000002|03/01/2024|Vente|10000,00||||B007|CHEVRY DESSOUS|1170|CHEVRY|01|103||B|1782||||||||||||0||||||S||115
|||||||000001|08/01/2024|Vente|249000,00||||B086|PIN HAMEAU|1290|LAIZ|01|203||C|1065||||||||||||0||||||S||497
|||||||000001|03/01/2024|Vente|329500,00|29||PL|0500|DU JURA|1170|GEX|01|173||AI|551||175||29||||||||2|2|Appartement||89|4|||
|||||||000001|03/01/2024|Vente|329500,00|9001||PL|0500|DU JURA|1170|GEX|01|173||AI|551||50||||||||||1|3|Dépendance||0|0|||
|||||||000001|03/01/2024|Vente|329500,00|29||PL|0500|DU JURA|1170|GEX|01|173||AI|551||175||29||||||||2|3|Dépendance||0|0|||
|||||||000001|03/01/2024|Vente|329500,00|29||PL|0500|DU JURA|1170|GEX|01|173||AI|551||175||29||||||||2|3|Dépendance||0|0|||
|||||||000001|09/01/2024|Vente|20000,00||||B579|AU CHAUME|1110|PLATEAU D'HAUTEVILLE|01|185|186|A|4||||||||||||0||||||BR||1584
|||||||000001|09/01/2024|Vente|20000,00||||B606|LES FATES|1110|PLATEAU D'HAUTEVILLE|01|185|186|A|32||||||||||||0||||||BR||188

In [3]:
import pandas as pd

df = pd.read_csv("/home/onyxia/work/cache/ValeursFoncieres-2024.txt", sep="|")

/tmp/ipykernel_45074/938475162.py:3: DtypeWarning: Columns (18,23,24,26,28,30,31,33,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/home/onyxia/work/cache/ValeursFoncieres-2024.txt", sep="|")

In [4]:
df

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2024,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,P,NaN,99.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,03/01/2024,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,115.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,08/01/2024,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,497.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/01/2024,Vente,...,NaN,2,2.0,Appartement,NaN,89.0,4.0,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/01/2024,Vente,...,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3489144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17/10/2024,Adjudication,...,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
3489145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,30/08/2024,Vente,...,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
3489146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,30/08/2024,Vente,...,NaN,3,2.0,Appartement,NaN,130.0,3.0,NaN,NaN,NaN
3489147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,05/09/2024,Adjudication,...,NaN,1,2.0,Appartement,NaN,10.0,1.0,NaN,NaN,NaN
3489148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15/02/2024,Adjudication,...,NaN,1,4.0,Local industriel. commercial ou assimilé,NaN,36.0,0.0,NaN,NaN,NaN

In [5]:
colonnes_utiles = [
    "Date mutation", 
    "Nature mutation", 
    "Valeur fonciere", 
    "No voie", 
    "Voie",
    "Type de voie",
    "Code voie",
    "Code postal", 
    "Commune",
    "B/T/Q",
    "Code commune",
    "Code departement",
    "Type local", 
    "Code type local",
    "Surface reelle bati", 
    "Nombre pieces principales", 
    "Surface terrain"
]

df_filtre = df[colonnes_utiles]

print(df_filtre.head())

  Date mutation Nature mutation Valeur fonciere  No voie            Voie  \
0    02/01/2024           Vente          346,50      NaN      LE DELIVRE
1    03/01/2024           Vente        10000,00      NaN  CHEVRY DESSOUS
2    08/01/2024           Vente       249000,00      NaN      PIN HAMEAU
3    03/01/2024           Vente       329500,00     29.0         DU JURA
4    03/01/2024           Vente       329500,00   9001.0         DU JURA

  Type de voie Code voie  Code postal Commune B/T/Q  Code commune  \
0          NaN      B020       1230.0  CHALEY   NaN            76
1          NaN      B007       1170.0  CHEVRY   NaN           103
2          NaN      B086       1290.0    LAIZ   NaN           203
3           PL      0500       1170.0     GEX   NaN           173
4           PL      0500       1170.0     GEX   NaN           173

  Code departement   Type local  Code type local  Surface reelle bati  \
0                1          NaN              NaN                  NaN
1                1          NaN              NaN                  NaN
2                1          NaN              NaN                  NaN
3                1  Appartement              2.0                 89.0
4                1   Dépendance              3.0                  0.0

   Nombre pieces principales  Surface terrain
0                        NaN             99.0
1                        NaN            115.0
2                        NaN            497.0
3                        4.0              NaN
4                        0.0              NaN

In [6]:
#Vérification du pourcentage de valeurs manquantes dans Code departement avant de filtrer les data d idf
taux_na = df_filtre["Code departement"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes dans Code departement : {taux_na:.2f}%")

Pourcentage de valeurs manquantes dans Code departement : 0.00%

In [7]:

#Nettoyage de la Colonne Code departement
df_filtre["Code departement"] = df_filtre["Code departement"].astype(str).str.strip()

# Filtrage des communes en ile de france 
codes_idf = ["75", "77", "78", "91", "92", "93", "94", "95"]
idf = df_filtre[df_filtre["Code departement"].isin(codes_idf)]

/tmp/ipykernel_45074/2204082965.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtre["Code departement"] = df_filtre["Code departement"].astype(str).str.strip()

In [8]:
idf

,Date mutation,Nature mutation,Valeur fonciere,No voie,Voie,Type de voie,Code voie,Code postal,Commune,B/T/Q,Code commune,Code departement,Type local,Code type local,Surface reelle bati,Nombre pieces principales,Surface terrain
2655797,02/01/2024,Vente,"98000,00",9002.0,JEAN GOUJON,RUE,0248,77350.0,LE MEE SUR SEINE,NaN,285,77,Dépendance,3.0,0.0,0.0,NaN
2655798,02/01/2024,Vente,"98000,00",177.0,JEAN GOUJON,RUE,0248,77350.0,LE MEE SUR SEINE,NaN,285,77,Dépendance,3.0,0.0,0.0,NaN
2655799,02/01/2024,Vente,"98000,00",177.0,JEAN GOUJON,RUE,0248,77350.0,LE MEE SUR SEINE,NaN,285,77,Appartement,2.0,66.0,3.0,NaN
2655800,02/01/2024,Vente,"163574,00",193.0,DU CHATEAU D EAU,RUE,0040,77390.0,FOUJU,NaN,195,77,Appartement,2.0,57.0,3.0,NaN
2655801,02/01/2024,Vente,"163574,00",193.0,DU CHATEAU D EAU,RUE,0040,77390.0,FOUJU,NaN,195,77,Dépendance,3.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3489144,17/10/2024,Adjudication,"17600,00",176.0,DE L UNIVERSITE,RUE,9527,75007.0,PARIS 07,NaN,107,75,Dépendance,3.0,0.0,0.0,NaN
3489145,30/08/2024,Vente,"2480000,00",7.0,JACOB,RUE,4771,75006.0,PARIS 06,NaN,106,75,Dépendance,3.0,0.0,0.0,NaN
3489146,30/08/2024,Vente,"2480000,00",7.0,JACOB,RUE,4771,75006.0,PARIS 06,NaN,106,75,Appartement,2.0,130.0,3.0,NaN
3489147,05/09/2024,Adjudication,"150000,00",100.0,BALARD,RUE,0639,75015.0,PARIS 15,NaN,115,75,Appartement,2.0,10.0,1.0,NaN
3489148,15/02/2024,Adjudication,"352000,00",45.0,DE BELLEVILLE,BD,0832,75011.0,PARIS 11,NaN,111,75,Local industriel. commercial ou assimilé,4.0,36.0,0.0,NaN

In [9]:
valeurs_uniques = idf["Type local"].unique()
print(valeurs_uniques)

['Dépendance' 'Appartement' 'Maison' nan
 'Local industriel. commercial ou assimilé']

In [10]:
#Vérification du pourcentage de valeurs manquantes dans type local avant de filtrer les appartement et maison
taux_na = idf["Code type local"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes dans Type local en IDF : {taux_na:.2f}%")

Pourcentage de valeurs manquantes dans Type local en IDF : 19.67%

In [11]:
#Vérification du pourcentage de valeurs manquantes dans type local avant de filtrer les appartement et maison
taux_na = idf["Surface reelle bati"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes dans Surface reelle bati en IDF: {taux_na:.2f}%")

Pourcentage de valeurs manquantes dans Surface reelle bati en IDF: 19.71%

In [12]:
 idf = idf[idf["Surface reelle bati"].notna()]
 idf["Surface reelle bati"] = pd.to_numeric(idf["Surface reelle bati"])
 idf = idf[idf["Surface reelle bati"] > 0]
 print(idf["Surface reelle bati"].min())

1.0

/tmp/ipykernel_45074/634404314.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idf["Surface reelle bati"] = pd.to_numeric(idf["Surface reelle bati"])

In [13]:
idf

,Date mutation,Nature mutation,Valeur fonciere,No voie,Voie,Type de voie,Code voie,Code postal,Commune,B/T/Q,Code commune,Code departement,Type local,Code type local,Surface reelle bati,Nombre pieces principales,Surface terrain
2655799,02/01/2024,Vente,"98000,00",177.0,JEAN GOUJON,RUE,0248,77350.0,LE MEE SUR SEINE,NaN,285,77,Appartement,2.0,66.0,3.0,NaN
2655800,02/01/2024,Vente,"163574,00",193.0,DU CHATEAU D EAU,RUE,0040,77390.0,FOUJU,NaN,195,77,Appartement,2.0,57.0,3.0,NaN
2655803,04/01/2024,Vente,"136200,00",45.0,CAMILLE FLAMMARION,RUE,0220,77000.0,MELUN,B,288,77,Appartement,2.0,32.0,2.0,NaN
2655806,04/01/2024,Vente,"136200,00",45.0,CAMILLE FLAMMARION,RUE,0220,77000.0,MELUN,B,288,77,Appartement,2.0,30.0,2.0,NaN
2655807,04/01/2024,Vente,"305000,00",12.0,AUGUSTE RENOIR,RUE,0020,77000.0,ROCHETTE(LA),NaN,389,77,Maison,1.0,87.0,5.0,628.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3489142,27/12/2024,Vente,"154000,00",88.0,RICHARD LENOIR,BD,8208,75011.0,PARIS 11,NaN,111,75,Appartement,2.0,29.0,2.0,NaN
3489143,17/12/2024,Vente,"220000,00",50.0,JENNER,RUE,4966,75013.0,PARIS 13,NaN,113,75,Appartement,2.0,18.0,1.0,NaN
3489146,30/08/2024,Vente,"2480000,00",7.0,JACOB,RUE,4771,75006.0,PARIS 06,NaN,106,75,Appartement,2.0,130.0,3.0,NaN
3489147,05/09/2024,Adjudication,"150000,00",100.0,BALARD,RUE,0639,75015.0,PARIS 15,NaN,115,75,Appartement,2.0,10.0,1.0,NaN
3489148,15/02/2024,Adjudication,"352000,00",45.0,DE BELLEVILLE,BD,0832,75011.0,PARIS 11,NaN,111,75,Local industriel. commercial ou assimilé,4.0,36.0,0.0,NaN

In [14]:
#Vérification du pourcentage de valeurs manquantes dans type local avant de filtrer les appartement et maison
taux_na = idf["Type local"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes dans Type local du data frame idf : {taux_na:.2f}%")

Pourcentage de valeurs manquantes dans Type local du data frame idf : 0.00%

In [15]:
idf = idf[idf["Type local"] != "Local industriel. commercial ou assimilé"]

In [16]:
idf

,Date mutation,Nature mutation,Valeur fonciere,No voie,Voie,Type de voie,Code voie,Code postal,Commune,B/T/Q,Code commune,Code departement,Type local,Code type local,Surface reelle bati,Nombre pieces principales,Surface terrain
2655799,02/01/2024,Vente,"98000,00",177.0,JEAN GOUJON,RUE,0248,77350.0,LE MEE SUR SEINE,NaN,285,77,Appartement,2.0,66.0,3.0,NaN
2655800,02/01/2024,Vente,"163574,00",193.0,DU CHATEAU D EAU,RUE,0040,77390.0,FOUJU,NaN,195,77,Appartement,2.0,57.0,3.0,NaN
2655803,04/01/2024,Vente,"136200,00",45.0,CAMILLE FLAMMARION,RUE,0220,77000.0,MELUN,B,288,77,Appartement,2.0,32.0,2.0,NaN
2655806,04/01/2024,Vente,"136200,00",45.0,CAMILLE FLAMMARION,RUE,0220,77000.0,MELUN,B,288,77,Appartement,2.0,30.0,2.0,NaN
2655807,04/01/2024,Vente,"305000,00",12.0,AUGUSTE RENOIR,RUE,0020,77000.0,ROCHETTE(LA),NaN,389,77,Maison,1.0,87.0,5.0,628.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3489140,27/12/2024,Vente,"154000,00",88.0,RICHARD LENOIR,BD,8208,75011.0,PARIS 11,NaN,111,75,Appartement,2.0,40.0,2.0,NaN
3489142,27/12/2024,Vente,"154000,00",88.0,RICHARD LENOIR,BD,8208,75011.0,PARIS 11,NaN,111,75,Appartement,2.0,29.0,2.0,NaN
3489143,17/12/2024,Vente,"220000,00",50.0,JENNER,RUE,4966,75013.0,PARIS 13,NaN,113,75,Appartement,2.0,18.0,1.0,NaN
3489146,30/08/2024,Vente,"2480000,00",7.0,JACOB,RUE,4771,75006.0,PARIS 06,NaN,106,75,Appartement,2.0,130.0,3.0,NaN
3489147,05/09/2024,Adjudication,"150000,00",100.0,BALARD,RUE,0639,75015.0,PARIS 15,NaN,115,75,Appartement,2.0,10.0,1.0,NaN

In [17]:
#Vérification du pourcentage de valeurs manquantes pour les numéro de voie
taux_na = idf["No voie"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes pour les numéro de voie : {taux_na:.2f}%")

#Vérification du pourcentage de valeurs manquantes pour le nom des voies
taux_na = idf["Voie"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes pour le nom des voies : {taux_na:.2f}%")

#Vérification du pourcentage de valeurs manquantes pour les types de voies 
taux_na = idf["Type de voie"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes pour les types de voies  : {taux_na:.2f}%")

#Vérification du pourcentage de valeurs manquantes pour codes postaux
taux_na = idf["Code postal"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes pour les types de voies  : {taux_na:.2f}%")

Pourcentage de valeurs manquantes pour les numéro de voie : 0.69%
Pourcentage de valeurs manquantes pour le nom des voies : 0.00%
Pourcentage de valeurs manquantes pour les types de voies  : 1.32%
Pourcentage de valeurs manquantes pour les types de voies  : 0.00%

In [27]:
idf["x"] = pd.NA
idf["y"] = pd.NA

idf["Code postal"] = idf["Code postal"].astype(str).str.replace(".0", "", regex=False).str.strip()
idf["No voie"] = idf["No voie"].astype(str).str.replace(".0", "", regex=False).str.strip()

idf["Type de voie"] = idf["Type de voie"].fillna("").astype(str).str.strip()
idf["Voie"] = idf["Voie"].fillna("").astype(str).str.strip()

# Créer une colonne adresse propre
idf["adresse"] = (
    idf["No voie"] + " " +
    idf["Type de voie"] + " " +
    idf["Voie"]
).str.replace(" +", " ", regex=True).str.strip()

/tmp/ipykernel_45074/706913884.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idf["x"] = pd.NA
/tmp/ipykernel_45074/706913884.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idf["y"] = pd.NA
/tmp/ipykernel_45074/706913884.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idf["Code postal"] = idf["Code postal"].astype(str).str.replace(".0", "", regex=False).str.strip()
/tmp/ipykernel_45074/706913884.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idf["No voie"] = idf["No voie"].astype(str).str.replace(".0", "", regex=False).str.strip()
/tmp/ipykernel_45074/706913884.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idf["Type de voie"] = idf["Type de voie"].fillna("").astype(str).str.strip()
/tmp/ipykernel_45074/706913884.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idf["Voie"] = idf["Voie"].fillna("").astype(str).str.strip()
/tmp/ipykernel_45074/706913884.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idf["adresse"] = (

In [ ]:
import requests
import time

for index, row in idf.iterrows():
    adresse = str(row["adresse"]).strip()
    postcode = str(row["Code postal"]).strip()
    url_ban = f"https://api-adresse.data.gouv.fr/search/?q={adresse.replace(' ', '+')}&postcode={postcode}"

    try:
        # Envoyer la requête
        req = requests.get(url_ban, timeout=5)
        localisation_insee = req.json()

        features = localisation_insee.get('features')

        # Si on a au moins un résultat
        if features and len(features) > 0:
            v = features[0].get('properties', {})
            idf.at[index, "x"] = v.get("x")
            idf.at[index, "y"] = v.get("y")
            print(f" Coordonnée pour l'adresse : {adresse} trouvées")
        else:
            print(f" Aucun résultat pour : {adresse} ({postcode})")

    except Exception as e:
        print(f"Erreur sur la ligne {index} ({adresse}) : {e}")

  # Sauvegarde automatique toutes les 1000 lignes
    if index % 1000 == 0 and index > 0:
        idf.to_csv(save_path, index=False)
        print(f"Sauvegarde automatique après {index} lignes")

    time.sleep(0.2)

# Sauvegarde finale à la fin
idf.to_csv(save_path, index=False)
print("Sauvegarde finale terminée")

 Coordonnée pour l'adresse : 177 RUE JEAN GOUJON trouvées
 Coordonnée pour l'adresse : 193 RUE DU CHATEAU D EAU trouvées
 Coordonnée pour l'adresse : 45 RUE CAMILLE FLAMMARION trouvées
 Coordonnée pour l'adresse : 45 RUE CAMILLE FLAMMARION trouvées
 Coordonnée pour l'adresse : 12 RUE AUGUSTE RENOIR trouvées
 Coordonnée pour l'adresse : 14 RUE DE PONTHIERRY trouvées
 Coordonnée pour l'adresse : 14 RUE DE PONTHIERRY trouvées
 Coordonnée pour l'adresse : 5238 LES PIERRIERES trouvées
 Coordonnée pour l'adresse : 30 RUE GRANDE trouvées
 Coordonnée pour l'adresse : 12 ALL MARCHAIS DE LA CROIX trouvées
 Coordonnée pour l'adresse : 5 RUE DU REVEILLON trouvées
 Coordonnée pour l'adresse : 2 RUE DES ACACIAS trouvées
 Coordonnée pour l'adresse : 6 RUE DES LOIRS trouvées
 Coordonnée pour l'adresse : 55 RUE HECTOR BERLIOZ trouvées
 Coordonnée pour l'adresse : 14 GRANDE RUE VILLEMENEUX trouvées

KeyboardInterrupt:

In [ ]:
#Vérification du pourcentage de valeurs manquantes pour les coordonnées
taux_na = idf["x"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes pour les coordonnées : {taux_na:.2f}%")

idf = idf[idf["x"].notna()]